-- BGS — 200 profiled members for Jinja City (10 per depot; first 5 per depot are the leaders).
-- Profile-first: no money yet, everyone is Pending. Run ONCE in Supabase (after the depot_role migration).
BEGIN;
INSERT INTO members
  (id, name, phone, district, district_name, sub_county, parish, depot, depot_role, gender, amount, disbursement_date, status)
VALUES
(next_member_id('JJA'), 'WAMBI SALIMA', '0703742468', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Bugembe', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MENYA LYDIA', '0721665869', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Bugembe', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAKOOLI DAVID', '0731761298', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Bugembe', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKOSE MICHAEL', '0759727175', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Bugembe', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BATAMBUZE RUTH', '0736250183', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwenda TC Ward', 'Bugembe', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI REHEMA', '0726609292', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Bugembe', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WANDERA ROSE', '0705713900', 'JJA', 'Jinja City', 'Jinja North Division', 'Namizi Ward', 'Bugembe', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BALIDAWA SCOVIA', '0758471767', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Bugembe', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI SHARIF', '0710701858', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Bugembe', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WANDERA DANIEL', '0775587104', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Bugembe', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BATAMBUZE FARIDAH', '0712704949', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Buwenda', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAGANDA GEOFREY', '0795813030', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Buwenda', 'Vice Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NABIRYE DANIEL', '0793748590', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Buwenda', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'LUBEGA GEOFREY', '0714957584', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Buwenda', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ISABIRYE DANIEL', '0700527162', 'JJA', 'Jinja City', 'Jinja North Division', 'Kibibi Ward', 'Buwenda', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMAGANDA MARTIN', '0718968397', 'JJA', 'Jinja City', 'Jinja North Division', 'Mafubira Ward', 'Buwenda', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMULONDO REHEMA', '0765012694', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwenda TC Ward', 'Buwenda', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ALIYINZA MADINA', '0766125443', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Buwenda', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKUTU PAUL', '0707348988', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Buwenda', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MWEBAZA SANDRA', '0770549126', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Buwenda', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WABWIRE AISHA', '0785352254', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Central', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA PROSCOVIA', '0780304601', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyange Ward', 'Central', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BATAMBUZE PHIONA', '0775592136', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwekula Ward', 'Central', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NGOBI FRED', '0729594578', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Central', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO ALI', '0774639145', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwekula Ward', 'Central', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KASADHA SWABRA', '0774006964', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Central', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKAMA JULIET', '0755077509', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Central', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI FAHAD', '0720762158', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Central', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI YASIN', '0735341465', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Central', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KISIGE MAUREEN', '0761628556', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Central', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAWOGOLE PAUL', '0771490542', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Danida', 'Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BATAMBUZE ZULAIKA', '0706526045', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Danida', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KASADHA SAID', '0752553562', 'JJA', 'Jinja City', 'Jinja North Division', 'Ivunamba Ward', 'Danida', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BAKAKI SUUDI', '0722204346', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Danida', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUSOBYA NASSER', '0760062395', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Danida', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BIRIBAWA BRENDA', '0789595244', 'JJA', 'Jinja City', 'Jinja North Division', 'Namizi Ward', 'Danida', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GONZA SHADIA', '0763449212', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Danida', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA VINCENT', '0729463455', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Danida', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA RASHID', '0726834541', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Danida', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ALIYINZA ROSE', '0759964028', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Danida', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GONZA JAMES', '0791833776', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Kibuye', 'Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKUTU IRENE', '0764571373', 'JJA', 'Jinja City', 'Jinja North Division', 'Namizi Ward', 'Kibuye', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MBAYO SYLVIA', '0707912609', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Kibuye', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUSOBYA FATUMA', '0774595185', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Kibuye', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BUDDE RASHID', '0763083201', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Kibuye', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO IRENE', '0792644196', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Kibuye', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BALIDAWA MAIMUNA', '0774145849', 'JJA', 'Jinja City', 'Jinja North Division', 'Katende Ward', 'Kibuye', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TIBENDA PROSCOVIA', '0784433162', 'JJA', 'Jinja City', 'Jinja North Division', 'Mafubira Ward', 'Kibuye', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TENYWA NASSER', '0769683264', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Kibuye', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAWOGOLE SANIA', '0723893446', 'JJA', 'Jinja City', 'Jinja North Division', 'Katende Ward', 'Kibuye', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WANDERA RASHID', '0774324742', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Kikaramoja', 'Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO GRACE', '0771915800', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Kikaramoja', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAMBI JOYCE', '0703756621', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Kikaramoja', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBI FALUKU', '0742598400', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Kikaramoja', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKAYE ZAKIA', '0706274041', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Kikaramoja', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAISWA MARIAM', '0781066681', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Kikaramoja', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'IZIMBA MOSES', '0728384929', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Kikaramoja', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KASADHA BRENDA', '0744249160', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Kikaramoja', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAISWA DEBORAH', '0779735240', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Kikaramoja', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBI SYLVIA', '0782721801', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba East', 'Kikaramoja', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KATAIKE ASIA', '0756257095', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Kimaka', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAKOOLI JOSHUA', '0720373782', 'JJA', 'Jinja City', 'Jinja North Division', 'Kibibi Ward', 'Kimaka', 'Vice Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BABIRYE ZULAIKA', '0748269243', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyange Ward', 'Kimaka', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKAMA NASIFA', '0779578735', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyange Ward', 'Kimaka', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAIGAGA IMMACULATE', '0714691817', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Kimaka', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BIRIBAWA SWABRA', '0733908690', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwenda TC Ward', 'Kimaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BALIDAWA MUSA', '0738292010', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Kimaka', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MWEBAZA EDWARD', '0709437704', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Kimaka', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTYABA SWABRA', '0756878530', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Kimaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBI HAWA', '0776221082', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Kimaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTYABA AGNES', '0791204010', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Loco', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BATEGANYA IDI', '0715916891', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyange Ward', 'Loco', 'Vice Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAWOGOLE MAIMUNA', '0712736482', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Loco', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANGOBI JAMIRA', '0791304471', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Loco', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TIBENDA LAWRENCE', '0732455062', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Loco', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ZIBONDO RUTH', '0726001693', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Loco', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUSOBYA MADINA', '0746720996', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Loco', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GONZA VINCENT', '0799009557', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Loco', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MBAYO NAIMA', '0724949976', 'JJA', 'Jinja City', 'Jinja North Division', 'Namizi Ward', 'Loco', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKONO SCOVIA', '0719123412', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Loco', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUSOBYA GRACE', '0723560320', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Lubas', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NABIRYE ABDUL', '0797620928', 'JJA', 'Jinja City', 'Jinja North Division', 'Katende Ward', 'Lubas', 'Vice Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKABIRE HAMIDU', '0722144737', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Lubas', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ISIKO HELLEN', '0778231683', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Lubas', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BUKENYA IBRAHIM', '0790844158', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyange Ward', 'Lubas', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAWOGOLE RESTY', '0764542769', 'JJA', 'Jinja City', 'Jinja North Division', 'Kibibi Ward', 'Lubas', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KASADHA ANNET', '0727806624', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Lubas', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA MAUREEN', '0746294110', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba East', 'Lubas', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAIGAGA ZAINA', '0743407552', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Lubas', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MBAYO FARIDAH', '0751337546', 'JJA', 'Jinja City', 'Jinja North Division', 'Kibibi Ward', 'Lubas', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'IZIMBA MUSA', '0745725186', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Masese', 'Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ISABIRYE ASIA', '0760881010', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Masese', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'LUBEGA SANDRA', '0786326052', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Masese', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBI SANDRA', '0714154158', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Masese', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKOSE ABDALLAH', '0787863197', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Masese', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MWEBAZA TOM', '0728694498', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Masese', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NABIRYE MUZAMIRU', '0761673641', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Masese', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAKIRYA MUZAMIRU', '0737996935', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Masese', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KIRUNDA HADIJAH', '0742999567', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Masese', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BIRIBAWA EDITH', '0744260549', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Masese', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BUKENYA SALIMA', '0793635656', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Mpambire', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI STELLA', '0719478052', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Mpambire', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA IMMACULATE', '0730890616', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Mpambire', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMULONDO SHAFIK', '0701228722', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Mpambire', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO MAUREEN', '0769099892', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Mpambire', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKAYE JOSHUA', '0739909264', 'JJA', 'Jinja City', 'Jinja North Division', 'Nawangoma Ward', 'Mpambire', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAMBI RAMADHAN', '0757094756', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Mpambire', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUGAYA TWAHA', '0730218306', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Mpambire', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAGOMBE ZAITUN', '0741861424', 'JJA', 'Jinja City', 'Jinja North Division', 'Nawangoma Ward', 'Mpambire', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'IZIMBA TOM', '0765086152', 'JJA', 'Jinja City', 'Jinja North Division', 'Namizi Ward', 'Mpambire', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TENYWA WINNIE', '0718439260', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Mpumudde', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMAGANDA HELLEN', '0784806509', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Mpumudde', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TENYWA WILSON', '0720011295', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Mpumudde', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KIRUNDA MAUREEN', '0789835902', 'JJA', 'Jinja City', 'Jinja North Division', 'Nawangoma Ward', 'Mpumudde', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MENYA RUTH', '0704388775', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Mpumudde', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAMBI JUMA', '0732590102', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwenda TC Ward', 'Mpumudde', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMAGANDA SUUDI', '0733847515', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Mpumudde', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NABIRYE DOREEN', '0769640529', 'JJA', 'Jinja City', 'Jinja North Division', 'Wanyama Ward', 'Mpumudde', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GONZA IRENE', '0791352291', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwekula Ward', 'Mpumudde', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KAGODA NASIFA', '0716601152', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwenda TC Ward', 'Mpumudde', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKAMA IDI', '0705605776', 'JJA', 'Jinja City', 'Jinja North Division', 'Ivunamba Ward', 'Nalufenya', 'Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ZIBONDO SULA', '0749895284', 'JJA', 'Jinja City', 'Jinja North Division', 'Nawangoma Ward', 'Nalufenya', 'Vice Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKABIRE GEORGE', '0727692483', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Nalufenya', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'IZIMBA FRED', '0765613717', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Nalufenya', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ISABIRYE TAUSI', '0765695265', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Nalufenya', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUGAYA SWABRA', '0741738291', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Nalufenya', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUSOBYA RASHID', '0768941143', 'JJA', 'Jinja City', 'Jinja North Division', 'Namizi Ward', 'Nalufenya', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKAYE RAMULA', '0777342601', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Nalufenya', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKUTU VINCENT', '0718339393', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Nalufenya', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KIRUNDA JULIET', '0791357964', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Nalufenya', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAIGAGA VINCENT', '0705089307', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Nile', 'Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAKIRYA ZAKIA', '0713188091', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Nile', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKEBA PROSSY', '0736228137', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Nile', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KAWUDHA IRENE', '0703718694', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Nile', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTYABA GEOFREY', '0742341974', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Nile', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKAMA RAMADHAN', '0723444239', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Nile', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ISIKO SIMON', '0719984974', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Nile', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GONZA RAMULA', '0783513688', 'JJA', 'Jinja City', 'Jinja North Division', 'Katende Ward', 'Nile', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NABIRYE RUTH', '0726156554', 'JJA', 'Jinja City', 'Jinja North Division', 'Katende Ward', 'Nile', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUKOSE JAMIRA', '0738971325', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwekula Ward', 'Nile', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAMBUZI CHRISTINE', '0746863948', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba East', 'Rippon', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBI RAMADHAN', '0774006569', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Rippon', 'Vice Chairperson', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO EDWARD', '0718274507', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Rippon', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NGOBI SADAT', '0715295302', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Rippon', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MENYA BRENDA', '0719020445', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Rippon', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO MAIMUNA', '0782547498', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Rippon', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BABIRYE FRANCIS', '0759662856', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Rippon', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUGAYA DANIEL', '0736407320', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Rippon', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAAKO JULIET', '0742603211', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Rippon', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI FAHAD', '0763816605', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Rippon', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUKOSE HADIJAH', '0770316305', 'JJA', 'Jinja City', 'Jinja North Division', 'Mafubira Ward', 'Rubaga', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MULINDA JENNIFER', '0703246879', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Rubaga', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBI HUSSEIN', '0701722015', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba West', 'Rubaga', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'LUBEGA REHEMA', '0750856985', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Rubaga', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ISIKO NASSER', '0755441998', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Rubaga', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANGOBI BASHIR', '0714523879', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Rubaga', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WABWIRE ISAAC', '0704403575', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Rubaga', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAIGAGA FLORENCE', '0771018510', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Rubaga', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKAYE AGNES', '0792379408', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Rubaga', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUGAYA FRANCIS', '0744593892', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Rubaga', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKAYE ESTHER', '0710043521', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Soweto', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TIBENDA MAUREEN', '0709166628', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Soweto', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WABWIRE YUSUF', '0731827524', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Soweto', 'Treasurer', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI WILSON', '0747361502', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Soweto', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANDHEGO IVAN', '0799626190', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Soweto', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BALIDAWA ALI', '0732054111', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Soweto', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTESI REHEMA', '0725902522', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Soweto', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'LUBEGA JOYCE', '0781628436', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Soweto', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GABULA PHIONA', '0706131027', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja East', 'Soweto', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KISIGE ROSE', '0797842495', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli East', 'Soweto', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BABIRYE JULIET', '0753493719', 'JJA', 'Jinja City', 'Jinja North Division', 'Budhumbuli West', 'Wairaka', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTYABA SANDRA', '0762254904', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Wairaka', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ALIYINZA SCOVIA', '0789713009', 'JJA', 'Jinja City', 'Jinja South Division', 'Masese Ward', 'Wairaka', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'IZIMBA RICHARD', '0779377341', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba East', 'Wairaka', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TENYWA SAID', '0798276049', 'JJA', 'Jinja City', 'Jinja South Division', 'Kimaka Ward', 'Wairaka', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'TIBENDA JAMIRA', '0753394906', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Wairaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NABIRYE WINNIE', '0710992894', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Wairaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NKONO TAUSI', '0743546201', 'JJA', 'Jinja City', 'Jinja North Division', 'Namulesa Ward', 'Wairaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA FAHAD', '0735509304', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba East', 'Wairaka', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMBWEIRA AMINA', '0782935099', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Wairaka', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MBAYO SALIMA', '0722163394', 'JJA', 'Jinja City', 'Jinja North Division', 'Mafubira Ward', 'Walukuba', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'WAISWA ANNET', '0737801611', 'JJA', 'Jinja City', 'Jinja North Division', 'Buwagi (Kakyomya)', 'Walukuba', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUSOBYA AMINA', '0795921360', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Walukuba', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'GONZA HENRY', '0740391976', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Walukuba', 'Secretary', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KIRUNDA ASIA', '0751106016', 'JJA', 'Jinja City', 'Jinja North Division', 'Ivunamba Ward', 'Walukuba', 'Publicity', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NANGOBI SALIMA', '0747540383', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Walukuba', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKABIRE MUZAMIRU', '0771649498', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Walukuba', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BALIDAWA MAIMUNA', '0796752778', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Walukuba', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUTYABA SANIA', '0739444545', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Walukuba', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'LUBEGA SWAIBU', '0720667570', 'JJA', 'Jinja City', 'Jinja South Division', 'Nalufenya Ward', 'Walukuba', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'ALIYINZA SWABRA', '0791230883', 'JJA', 'Jinja City', 'Jinja North Division', 'Mafubira Ward', 'Wanyange', 'Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KAAYA CHRISTINE', '0789403357', 'JJA', 'Jinja City', 'Jinja South Division', 'Maggwa Ward', 'Wanyange', 'Vice Chairperson', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BUKENYA ASIA', '0710413043', 'JJA', 'Jinja City', 'Jinja North Division', 'Nawangoma Ward', 'Wanyange', 'Treasurer', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MAWOGOLE TAUSI', '0706180252', 'JJA', 'Jinja City', 'Jinja South Division', 'Mpumudde Ward', 'Wanyange', 'Secretary', 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'BATAMBUZE MOSES', '0762419857', 'JJA', 'Jinja City', 'Jinja South Division', 'Central Jinja West', 'Wanyange', 'Publicity', 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'MUKABIRE CHRISTINE', '0799031899', 'JJA', 'Jinja City', 'Jinja South Division', 'Old Boma Ward', 'Wanyange', NULL, 'Female', 0, NULL, 'Active'),
(next_member_id('JJA'), 'NAMUGAYA SWAIBU', '0791449837', 'JJA', 'Jinja City', 'Jinja South Division', 'Walukuba East', 'Wanyange', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KATAIKE FAHAD', '0782484471', 'JJA', 'Jinja City', 'Jinja South Division', 'Lubaga Ward', 'Wanyange', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KINTU HAMIDU', '0720011822', 'JJA', 'Jinja City', 'Jinja North Division', 'Mafubira Ward', 'Wanyange', NULL, 'Male', 0, NULL, 'Active'),
(next_member_id('JJA'), 'KISIGE WILSON', '0752350276', 'JJA', 'Jinja City', 'Jinja North Division', 'Nakanyonyi Ward', 'Wanyange', NULL, 'Male', 0, NULL, 'Active');
UPDATE members SET registered_by = (SELECT id FROM users WHERE username='faruk' LIMIT 1) WHERE registered_by IS NULL;
COMMIT;